language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "1.8"
  - "2.5"
  - "3.3"
  - "4.5"
  - "5.11"
  - "6.5"
sudo: false
cache:
  directories:
    - node_modules
before_install:
  - "test ! -d node_modules || npm prune"
  - "test ! -d node_modules || npm rebuild"
script:
  - "npm run-script test-travis"
after_script:
  - "npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
